name:                hle-bot
version:             0.1.0.0
github:              "mtamc/hle-welcome"
license:             BSD3
author:              "Tam CARRE"
maintainer:          "Tam CARRE"
copyright:           "2022 Tam CARRE"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/mtamc/hle-welcome#readme>

dependencies:
- base-noprelude
- relude
- hspec
- hspec-contrib
- discord-haskell
- emoji
- unliftio
- text
- containers
- lens
- generic-lens
- mtl
- template-haskell
- data-default
- base-unicode-symbols
- safe-exceptions
- opaleye
- product-profunctors
- postgresql-simple
- dhall
- time
- openai-hs
- http-client
- http-client-tls
- vector
- servant >= 0.19.1

language: GHC2021

default-extensions:
- OverloadedStrings
- OverloadedLabels
- UnicodeSyntax
- NoFieldSelectors
- LambdaCase
- DuplicateRecordFields
- ViewPatterns
- BlockArguments
- DataKinds
- TypeOperators
- TypeFamilies
- OverloadedRecordDot

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hle-bot-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fwrite-ide-info
    - -hiedir=.hie
    dependencies:
    - hle-bot

